### ISSUE TITLE
Split `BlockBlobs` table

### ISSUE THREAD

**Issue by Boog900** [Cuprate/cuprate#282]
## What

The `BlockBlobs` table stores the serialized block blob, this issues is for splitting that table into a `BlockHeaderBlobs` and `BlockTxHashes`.

## Why 

The block blob contains the miner tx blob which means we are duplicating miner txs in the DB. Splitting the table also means we wouldn't have to parse the full block when we need to retrieve tx blobs for the block.

**Comment by Asurar0** [comment]
I would appreciate being assigned to this issue.

**Comment by Boog900** [comment]
@Asurar0 I am having problems with matrix but I saw your message.

You will need to add another field to `BlockInfo`, the miner transactions index. You can then use this index to look up the miner tx
