### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by dedicated-1** [Cuprate/cuprate#29]
Hello, I heard on monero.social (matrix chat) that you were looking for people to help with development, but I only know Javascript/PHP.
I've been playing with Rust for only a few weeks, do you think it's possible for me to contribute? Sorry for asking if it sounds silly.

**Comment by Boog900** [comment]
Hi, thanks for reaching out! 

Yes I would be grateful for any help, but you may struggle if you haven't done much Rust before. I think a good place to start would be to fix this [issue](https://github.com/monero-rs/monero-epee-bin-serde/issues/49), currently we use an epee lib not based on serde but I would prefer to move back to a serde lib if possible. To do this though we will have to fix the bugs in that lib. If you would like any help I am contactable on Matrix: boog900:monero.social
