### ISSUE TITLE
Should IPv6 be disabled by default ?

### ISSUE THREAD

**Issue by SyntheticBird45** [Cuprate/cuprate#99]
## IPv6 support

Q. Should we enable by default IPv6 support for Cuprate ?

An issue has been created since last year: https://github.com/monero-project/monero/issues/8818

I think this is a nice addition to Cuprate to have it enabled by default. It'll permit to grow the ipv6 network which will in the end encourage monerod users to enable it.

**Comment by Boog900** [comment]
Cuprate's P2P stack currently supports IPv6 and I can confirm I have maintained connections to IPv6 nodes, so this issue should be for if support should be turned off

**Comment by SyntheticBird45** [comment]
Closing. I don't see any reason to turn it off by default. An option should exist to disable it manually.
